import { Certificates, db, } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {

	await db.insert(Certificates).values([
		{
			provider: "Udemy",
			date: new Date("2023-03-06"),
			duration: "16.5 Hours",
			technologies: JSON.stringify(["Docker", "Jenkins", "Kubernetes", "Git", "CI/CD"]),
			certificateUrl: "https://www.udemy.com/certificate/UC-7ead730f-c8bb-4934-b190-9fae87c2439a/",
			title_en: "DevOps: Docker, Kubernetes, Jenkins, GitFlow CI/CD",
			description_en: "This certificate helped me understand the entire cycle from development to deployment. It also served as the basis for my university thesis, as I chose this topic.",
			title_es: "DevOps: Docker, Kubernetes, Jenkins, GitFlow CI/CD",
			description_es: "Este certificado me ayudó a comprender todo el ciclo desde el desarrollo hasta el despliegue. También fue la base de mi tesis universitaria, ya que elegí este tema.",
		},
		{
			provider: "Udemy",
			date: new Date("2025-02-23"),
			duration: "33 Hours",
			technologies: JSON.stringify(["React Native", "Navigation", "UI Components", "Zustand", "TanStack Query"]),
			certificateUrl: "https://www.udemy.com/certificate/UC-c8022ba9-0bda-4623-826b-6e0844ed6fd5/",
			title_en: "React Native CLI: Native Apps for iOS and Android",
			description_en: "I learned React Native out of curiosity for mobile development and my love for JavaScript and TypeScript. It was my first step into building native mobile apps.",
			title_es: "React Native CLI: Apps Nativas para iOS y Android",
			description_es: "Aprendí React Native por curiosidad sobre el desarrollo móvil y por mi amor a JavaScript y TypeScript. Fue mi primer paso para crear apps móviles nativas.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-03-12"),
			duration: "37.5 Hours",
			technologies: JSON.stringify(["TanStack Query"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/xfbvdfdjyn",
			title_en: "TanStack Query: A Powerful Asynchronous State Manager",
			description_en: "After discovering the power of TanStack Query in React Native, this course helped me better understand this powerful tool.",
			title_es: "TanStack Query: Un Potente Gestor de Estado Asíncrono",
			description_es: "Después de descubrir el poder de TanStack Query en React Native, este curso me ayudó a comprender mejor esta poderosa herramienta.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-03-29"),
			duration: "37.5 Hours",
			technologies: JSON.stringify(["Node.js", "MongoDB", "PostgreSQL", "Express", "Jest"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/j5egawmq6g",
			title_en: "Node.js: From Zero to Expert",
			description_en: "This course helped me master backend fundamentals, including building scalable APIs, working with databases, and applying architecture best practices.",
			title_es: "Node.js: De Cero a Experto",
			description_es: "Este curso me ayudó a dominar los fundamentos del backend, incluyendo la creación de APIs escalables, trabajo con bases de datos y aplicación de buenas prácticas de arquitectura.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-04"),
			duration: "25 Hours",
			technologies: JSON.stringify(["NestJS", "MongoDB", "PostgreSQL", "TypeORM", "Websockets"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/3cgst3u9dp",
			title_en: "NestJS: Scalable Backend Development with Node",
			description_en: "I learned everything from data validation to JWT authentication, middleware, guards, and WebSockets — all essential for building scalable backend systems.",
			title_es: "NestJS: Desarrollo Backend Escalable con Node",
			description_es: "Aprendí desde validación de datos hasta autenticación con JWT, middleware, guards y WebSockets — todo esencial para construir sistemas backend escalables.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-11"),
			duration: "6.5 Hours",
			technologies: JSON.stringify(["NestJS", "HTML Elements in Reports", "Charts and SVGs", "Tables"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/dvrvuuprxw",
			title_en: "NestJS + Reports: Generate PDFs from Node",
			description_en: "This course showed me how to create modern PDF reports using PDFMake — a major upgrade from tools like Crystal Reports that require external software.",
			title_es: "NestJS + Reportes: Generación de PDFs desde Node",
			description_es: "Este curso me mostró cómo crear reportes PDF modernos usando PDFMake — una gran mejora frente a herramientas como Crystal Reports que requieren software externo.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-12"),
			duration: "6.5 Hours",
			technologies: JSON.stringify(["SOLID", "Clean Code"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/npzuarkhzg",
			title_en: "SOLID Principles and Clean Code",
			description_en: "This course reinforced what I already knew about SOLID principles and Clean Code—fundamental concepts that every developer should keep in mind.",
			title_es: "Principios SOLID y Código Limpio",
			description_es: "Este curso reforzó lo que ya sabía sobre los principios SOLID y Código Limpio—conceptos fundamentales que todo desarrollador debe tener presentes.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-14"),
			duration: "11.5 Hours",
			technologies: JSON.stringify(["Git", "GitHub"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/latb73hhun",
			title_en: "GIT + GitHub: A Complete Version Control System from Scratch",
			description_en: "I took this course to explore specific Git topics such as conflict management, revert, reset, and overall safe practices when using Git.",
			title_es: "GIT + GitHub: Sistema de Control de Versiones desde Cero",
			description_es: "Tomé este curso para explorar temas específicos de Git como manejo de conflictos, revert, reset y prácticas seguras en general al usar Git.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-17"),
			duration: "10 Hours",
			technologies: JSON.stringify(["Design Patterns"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/hgjyrb4qae",
			title_en: "Design Patterns: Practical and Efficient Solutions",
			description_en: "I took time to give each design pattern the attention it deserved. This course helped me understand how to solve recurring problems more effectively.",
			title_es: "Patrones de Diseño: Soluciones Prácticas y Eficientes",
			description_es: "Me tomé el tiempo de dar a cada patrón de diseño la atención que merecía. Este curso me ayudó a entender cómo resolver problemas recurrentes de manera más efectiva.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-17"),
			duration: "12.5 Hours",
			technologies: JSON.stringify(["Jest"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/feu8t2qu4r",
			title_en: "NestJS + Testing: Unit and End-to-End (e2e) Testing",
			description_en: "I explored how to apply testing in backend systems using Jest, learning how to keep applications stable and error-free through automated tests.",
			title_es: "NestJS + Testing: Pruebas Unitarias y End-to-End (e2e)",
			description_es: "Exploré cómo aplicar pruebas en sistemas backend usando Jest, aprendiendo a mantener las aplicaciones estables y sin errores mediante tests automatizados.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-04-26"),
			duration: "14 Hours",
			technologies: JSON.stringify(["Docker", "GitHub Actions"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/b3dszxwct4",
			title_en: "Docker: A Practical Guide for Developers",
			description_en: "This course was a crucial step in understanding advanced Docker concepts like multi-stage builds and automated builds.",
			title_es: "Docker: Guía Práctica para Desarrolladores",
			description_es: "Este curso fue un paso clave para entender conceptos avanzados de Docker como las compilaciones multi-stage y builds automatizados.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-05-05"),
			duration: "20.5 Hours",
			technologies: JSON.stringify(["Nest", "Docker", "Kubernetes", "GKE", "Helm"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/buqepvjxme",
			title_en: "NestJS + Microservices: Scalable and Modular Applications",
			description_en: "This course showed me that microservices are ideal for large-scale infrastructures—not always necessary for every system but very interesting to explore.",
			title_es: "NestJS + Microservicios: Aplicaciones Escalables y Modulares",
			description_es: "Este curso me mostró que los microservicios son ideales para infraestructuras a gran escala—no siempre necesarios para todo sistema, pero muy interesantes de explorar.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-05-09"),
			duration: "25.5 Hours",
			technologies: JSON.stringify(["Astro"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/c9iw8igntk",
			title_en: "Astro: The Framework for Content-Focused Websites",
			description_en: "I took this course to showcase my projects with a modern web framework. Astro gave me the speed, simplicity, and flexibility I was looking for.",
			title_es: "Astro: El Framework para Sitios Web Enfocados en Contenido",
			description_es: "Tomé este curso para mostrar mis proyectos con un framework web moderno. Astro me dio la velocidad, simplicidad y flexibilidad que estaba buscando.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-05-11"),
			duration: "10 Hours",
			technologies: JSON.stringify(["NestJS", "Open AI API"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/xddwahomij",
			title_en: "OpenAI: Practical Exercises and Assistants with React + NestJS",
			description_en: "What interested me the most in this course was using an AI API with NestJS. The frontend part didn’t catch my attention but it was interesting to do it.",
			title_es: "OpenAI: Ejercicios Prácticos y Asistentes con React + NestJS",
			description_es: "Lo que más me interesó de este curso fue usar una API de inteligencia artificial con NestJS. La parte del frontend no me llamó tanto, pero fue interesante realizarla.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-05-11"),
			duration: "6 Hours",
			technologies: JSON.stringify(["Zustand"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/hpqsp0cxal",
			title_en: "Mini-Course Zustand: State Management for React",
			description_en: "Curious after using Zustand in React Native, I dove deeper to understand why it’s considered a modern replacement for Redux in many React projects.",
			title_es: "Mini-Curso Zustand: Gestión de Estado para React",
			description_es: "Tras usar Zustand en React Native, me dio curiosidad y quise profundizar para entender por qué se considera un reemplazo moderno de Redux en muchos proyectos React.",
		},
		{
			provider: "DevTalles",
			date: new Date("2025-05-12"),
			duration: "16 Hours",
			technologies: JSON.stringify(["Socket.io"]),
			certificateUrl: "https://cursos.devtalles.com/certificates/ercpez6xx8",
			title_en: "React: Real-Time Applications with Socket.io",
			description_en: "I focused on what I needed from this course: handling websockets and good practices with Socket.io, as the frontend content was not related to websockets and wasn’t what I was looking for.",
			title_es: "React: Aplicaciones en Tiempo Real con Socket.io",
			description_es: "Me enfoqué en lo que necesitaba de este curso: manejo de websockets y buenas prácticas con Socket.io, ya que la parte de frontend no trataba sobre websockets y no era lo que buscaba.",
		},

	]);

}
