export const CertificatesSeed = [
	{
		provider: "Udemy",
		date: new Date("2023-03-06"),
		duration: "16.5 Hours",
		technologies: JSON.stringify([
			"Docker",
			"Kubernetes",
			"Jenkins",
			"Git",
			"GitFlow",
			"CI/CD",
			"DevOps",
			"Automation",
			"AI Assistance"
		]),
		certificateUrl: "https://www.udemy.com/certificate/UC-7ead730f-c8bb-4934-b190-9fae87c2439a/",
		title_en: "DevOps: Docker, Kubernetes, Jenkins, GitFlow CI/CD",
		description_en:
			"Practical course focused on modern DevOps practices using Docker, Kubernetes, Jenkins, and GitFlow. It covers containerization, orchestration, and the automation of continuous integration and delivery pipelines. The course emphasizes the full software lifecycle, from development to deployment, and includes AI-assisted simulations for real-world scenarios such as technical interviews and strategy presentations.",
		title_es: "DevOps: Docker, Kubernetes, Jenkins, GitFlow CI/CD",
		description_es:
			"Curso práctico enfocado en las prácticas modernas de DevOps utilizando Docker, Kubernetes, Jenkins y GitFlow. Cubre la contenedorización, orquestación y automatización de pipelines de integración y entrega continua. El curso aborda el ciclo completo de desarrollo y despliegue de software, e incluye simulaciones asistidas por IA para escenarios reales como entrevistas técnicas y presentaciones estratégicas.",
	},
	{
		provider: "Udemy",
		date: new Date("2025-02-23"),
		duration: "33 Hours",
		technologies: JSON.stringify([
			"React Native",
			"TypeScript",
			"React Navigation",
			"Context API",
			"Axios",
			"JWT Authentication",
			"Google Maps SDK",
			"Apple Maps",
			"Camera API",
			"Image Gallery",
			"Animations",
			"Flexbox",
			"Custom Hooks",
			"Dark & Light Themes",
			"CRUD Operations",
			"API Consumption",
			"iOS Deployment",
			"Android Deployment"
		]),
		certificateUrl: "https://www.udemy.com/certificate/UC-c8022ba9-0bda-4623-826b-6e0844ed6fd5/",
		title_en: "React Native CLI: Native Apps for iOS and Android",
		description_en:
			"Comprehensive course focused on building native mobile applications using React Native CLI and TypeScript. It covers navigation, animations, context management, API consumption, authentication with JWT, theming, CRUD operations, and deployment to both iOS and Android platforms.",
		title_es: "React Native CLI: Apps Nativas para iOS y Android",
		description_es:
			"Curso integral enfocado en la creación de aplicaciones móviles nativas usando React Native CLI y TypeScript. Cubre navegación, animaciones, manejo de contexto, consumo de APIs, autenticación con JWT, temas, operaciones CRUD y despliegue en plataformas iOS y Android.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-03-12"),
		duration: "37.5 Hours",
		technologies: JSON.stringify([
			"TanStack Query",
			"React",
			"Axios",
			"React Hook Form",
			"State Management",
			"Optimistic Updates",
			"Pagination",
			"Infinite Scroll",
			"Prefetching",
			"Data Caching"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/xfbvdfdjyn",
		title_en: "TanStack Query: A Powerful Asynchronous State Manager",
		description_en:
			"Comprehensive course on TanStack Query, focused on managing asynchronous state and data fetching in React applications. It covers query and mutation management, error handling, caching strategies, pagination, infinite scroll, prefetching, optimistic updates, and integration with React Hook Form for dynamic forms.",
		title_es: "TanStack Query: Un Potente Gestor de Estado Asíncrono",
		description_es:
			"Curso completo sobre TanStack Query enfocado en la gestión del estado asíncrono y la obtención de datos en aplicaciones React. Cubre manejo de queries y mutaciones, control de errores, estrategias de caché, paginación, scroll infinito, prefetching, actualizaciones optimistas e integración con React Hook Form para formularios dinámicos.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-03-29"),
		duration: "37.5 Hours",
		technologies: JSON.stringify([
			"Node.js",
			"Express",
			"TypeScript",
			"MongoDB",
			"PostgreSQL",
			"Prisma",
			"Mongoose",
			"REST API",
			"WebSockets",
			"Clean Architecture",
			"Domain Driven Design",
			"Dependency Injection",
			"Axios",
			"JWT Authentication",
			"File System",
			"CRON Jobs",
			"Testing",
			"Jest",
			"CI/CD",
			"Railway Deployment"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/j5egawmq6g",
		title_en: "Node.js: From Zero to Expert",
		description_en:
			"Comprehensive backend development course focused on Node.js and modern server-side practices. It covers building RESTful APIs, implementing WebSockets, handling authentication with JWT, working with MongoDB and PostgreSQL databases, and applying Clean Architecture and Domain Driven Design principles. The course also includes testing with Jest, file handling, CRON automation, dependency injection, and deployment using Railway.",
		title_es: "Node.js: De Cero a Experto",
		description_es:
			"Curso completo de desarrollo backend enfocado en Node.js y las prácticas modernas del lado del servidor. Cubre la creación de APIs RESTful, implementación de WebSockets, autenticación con JWT, uso de bases de datos MongoDB y PostgreSQL, y aplicación de principios de Clean Architecture y Domain Driven Design. También incluye pruebas con Jest, manejo de archivos, tareas automáticas con CRON, inyección de dependencias y despliegue con Railway.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-04"),
		duration: "25 Hours",
		technologies: JSON.stringify([
			"NestJS",
			"Node.js",
			"TypeScript",
			"TypeORM",
			"PostgreSQL",
			"MongoDB",
			"REST API",
			"WebSockets",
			"JWT Authentication",
			"Guards",
			"Interceptors",
			"Exception Filters",
			"Dependency Injection",
			"Docker",
			"CORS",
			"DTOs",
			"Validation",
			"SOLID Principles",
			"Clean Architecture"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/3cgst3u9dp",
		title_en: "NestJS: Scalable Backend Development with Node",
		description_en:
			"Comprehensive backend development course using NestJS and TypeScript, focused on building modular and scalable server-side applications. It covers controllers, services, guards, interceptors, dependency injection, and authentication with JWT. The course also explores RESTful APIs, WebSockets, database integration with TypeORM, PostgreSQL, and MongoDB, along with validation, Dockerization, and best practices following the SOLID principles.",
		title_es: "NestJS: Desarrollo Backend Escalable con Node",
		description_es:
			"Curso completo de desarrollo backend con NestJS y TypeScript, enfocado en la creación de aplicaciones del lado del servidor modulares y escalables. Cubre controladores, servicios, guards, interceptores, inyección de dependencias y autenticación con JWT. También aborda APIs RESTful, WebSockets, integración de bases de datos con TypeORM, PostgreSQL y MongoDB, además de validaciones, dockerización y buenas prácticas basadas en los principios SOLID.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-11"),
		duration: "6.5 Hours",
		technologies: JSON.stringify([
			"NestJS",
			"Node.js",
			"PDFMake",
			"Prisma",
			"PostgreSQL",
			"Chart.js",
			"Docker",
			"PgAdmin",
			"QR Codes",
			"SVG",
			"HTML to PDF",
			"Data Visualization",
			"Tables",
			"Custom Reports"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/dvrvuuprxw",
		title_en: "NestJS + Reports: Generate PDFs from Node",
		description_en:
			"Technical course focused on generating professional and customizable PDF reports using NestJS and PDFMake. It covers layout design, tables, charts, QR codes, and SVG integration. The course also includes database connectivity with Prisma and PostgreSQL, HTML-to-PDF conversion, and Docker-based environments for data-driven report generation.",
		title_es: "NestJS + Reportes: Generación de PDFs desde Node",
		description_es:
			"Curso técnico enfocado en la generación de reportes PDF profesionales y personalizables utilizando NestJS y PDFMake. Cubre diseño de layouts, tablas, gráficas, códigos QR e integración de SVGs. También incluye conexión a bases de datos con Prisma y PostgreSQL, conversión de HTML a PDF y entornos con Docker para la creación de reportes basados en datos.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-12"),
		duration: "6.5 Hours",
		technologies: JSON.stringify([
			"SOLID Principles",
			"Clean Code",
			"Object-Oriented Programming",
			"Software Architecture",
			"Design Patterns",
			"Code Quality",
			"Refactoring",
			"Best Practices"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/npzuarkhzg",
		title_en: "SOLID Principles and Clean Code",
		description_en:
			"Foundational course focused on the SOLID principles of software design and clean coding practices. It covers the five SOLID principles—Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, and Dependency Inversion—along with concepts like technical debt, maintainability, and code readability. The course emphasizes writing scalable, modular, and easy-to-maintain code following industry best practices.",
		title_es: "Principios SOLID y Código Limpio",
		description_es:
			"Curso fundamental enfocado en los principios SOLID de diseño de software y las prácticas de código limpio. Cubre los cinco principios SOLID—Responsabilidad Única, Abierto/Cerrado, Sustitución de Liskov, Segregación de Interfaces e Inversión de Dependencias—además de conceptos como deuda técnica, mantenibilidad y legibilidad del código. El curso enfatiza la escritura de código escalable, modular y fácil de mantener siguiendo las mejores prácticas de la industria.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-14"),
		duration: "11.5 Hours",
		technologies: JSON.stringify([
			"Git",
			"GitHub",
			"Version Control",
			"Branching",
			"Rebase",
			"Stash",
			"Pull Requests",
			"Reflog",
			"Collaboration Workflows"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/latb73hhun",
		title_en: "GIT + GitHub: A Complete Version Control System from Scratch",
		description_en:
			"Comprehensive course covering version control with Git and remote collaboration using GitHub. It includes key concepts such as branching, merging, stashing, rebasing, revert, reset, and reflog, along with modern workflows involving pull requests, team collaboration, and repository management. The course emphasizes best practices for maintaining clean, organized, and recoverable project histories.",
		title_es: "GIT + GitHub: Sistema de Control de Versiones desde Cero",
		description_es:
			"Curso completo sobre control de versiones con Git y colaboración remota usando GitHub. Incluye conceptos clave como ramas, fusiones, stash, rebase, revert, reset y reflog, junto con flujos de trabajo modernos basados en pull requests, trabajo en equipo y gestión de repositorios. El curso enfatiza las mejores prácticas para mantener historiales de proyecto limpios, organizados y recuperables.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-17"),
		duration: "10 Hours",
		technologies: JSON.stringify([
			"Design Patterns",
			"TypeScript",
			"Object-Oriented Programming",
			"Creational Patterns",
			"Structural Patterns",
			"Behavioral Patterns",
			"Software Architecture",
			"Clean Code"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/hgjyrb4qae",
		title_en: "Design Patterns: Practical and Efficient Solutions",
		description_en:
			"This course provided an in-depth understanding of software design patterns and their real-world applications using TypeScript. It covered creational, structural, and behavioral patterns, offering practical examples and exercises to write clean, reusable, and scalable code. A must-have foundation for mastering object-oriented design and software architecture.",
		title_es: "Patrones de Diseño: Soluciones Prácticas y Eficientes",
		description_es:
			"Este curso brindó una comprensión profunda de los patrones de diseño de software y sus aplicaciones reales utilizando TypeScript. Cubre patrones creacionales, estructurales y de comportamiento, ofreciendo ejemplos y ejercicios prácticos para escribir código limpio, reutilizable y escalable. Una base esencial para dominar el diseño orientado a objetos y la arquitectura de software.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-17"),
		duration: "12.5 Hours",
		technologies: JSON.stringify([
			"NestJS",
			"Jest",
			"Unit Testing",
			"End-to-End Testing",
			"Mocking",
			"Test Coverage",
			"RESTful APIs",
			"Authentication Testing",
			"Authorization Testing",
			"Continuous Integration"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/feu8t2qu4r",
		title_en: "NestJS + Testing: Unit and End-to-End (E2E) Testing",
		description_en:
			"Comprehensive training on implementing automated testing in NestJS applications using Jest. The course covers unit and end-to-end (E2E) testing for controllers, services, and modules, including mock management, authentication and authorization tests, error handling, and coverage reporting. Focused on ensuring code quality, stability, and scalability in backend systems.",
		title_es: "NestJS + Testing: Pruebas Unitarias y End-to-End (E2E)",
		description_es:
			"Formación completa sobre la implementación de pruebas automatizadas en aplicaciones NestJS utilizando Jest. Cubre pruebas unitarias y end-to-end (E2E) para controladores, servicios y módulos, incluyendo manejo de mocks, pruebas de autenticación y autorización, manejo de errores y generación de reportes de cobertura. Enfocado en garantizar la calidad, estabilidad y escalabilidad del código en sistemas backend.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-04-26"),
		duration: "14 Hours",
		technologies: JSON.stringify([
			"Docker",
			"Docker CLI",
			"Docker Compose",
			"Buildx",
			"GitHub Actions",
			"CI/CD",
			"Digital Ocean",
			"Kubernetes (Intro)",
			"Containerization",
			"Image Automation"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/b3dszxwct4",
		title_en: "Docker: A Practical Guide for Developers",
		description_en:
			"Comprehensive training focused on mastering Docker for application containerization. Covers the creation and management of Dockerfiles, multi-container setups with Docker Compose, image optimization with Buildx, and deployment automation through GitHub Actions. Includes practical projects and an introductory module on Kubernetes for modern DevOps workflows.",
		title_es: "Docker: Guía Práctica para Desarrolladores",
		description_es:
			"Formación completa enfocada en dominar Docker para la contenerización de aplicaciones. Cubre la creación y gestión de Dockerfiles, entornos multi-contenedor con Docker Compose, optimización de imágenes con Buildx y automatización de despliegues mediante GitHub Actions. Incluye proyectos prácticos y un módulo introductorio a Kubernetes para flujos modernos de DevOps.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-05-05"),
		duration: "20.5 Hours",
		technologies: JSON.stringify([
			"NestJS",
			"Microservices Architecture",
			"TCP Transport",
			"NATS",
			"Prisma",
			"Docker",
			"Kubernetes",
			"Google Cloud (GKE)",
			"Helm",
			"Stripe",
			"CI/CD",
			"Message Queues",
			"Event-Driven Architecture"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/buqepvjxme",
		title_en: "NestJS + Microservices: Scalable and Modular Applications",
		description_en:
			"Advanced course focused on building distributed systems using NestJS and microservices architecture. Covers inter-service communication through message patterns, transport layers like TCP and NATS, and database segregation with Prisma. Includes Dockerization, Kubernetes deployment on GKE, CI/CD pipelines, secret management, and integrations with Stripe and Google Cloud services.",
		title_es: "NestJS + Microservicios: Aplicaciones Escalables y Modulares",
		description_es:
			"Curso avanzado enfocado en la construcción de sistemas distribuidos utilizando NestJS y arquitectura de microservicios. Cubre la comunicación entre servicios mediante patrones de mensajes, transportadores como TCP y NATS, y separación de bases de datos con Prisma. Incluye dockerización, despliegue en Kubernetes (GKE), pipelines CI/CD, gestión de secretos e integración con Stripe y servicios de Google Cloud.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-05-09"),
		duration: "25.5 Hours",
		technologies: JSON.stringify([
			"Astro",
			"TypeScript",
			"React",
			"Vue",
			"Solid.js",
			"TailwindCSS",
			"Zod",
			"AuthJS",
			"Astro DB",
			"Netlify",
			"Cloudflare",
			"SEO",
			"SSR",
			"MDX"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/c9iw8igntk",
		title_en: "Astro: The Framework for Content-Focused Websites",
		description_en:
			"Comprehensive course focused on building high-performance, content-driven web applications with Astro. Covers static generation, server-side and hybrid rendering, state persistence, authentication, and API integrations. Includes the use of multiple UI frameworks (React, Vue, Solid), Astro DB, and advanced optimization techniques for SEO and image handling.",
		title_es: "Astro: El Framework para Sitios Web Enfocados en Contenido",
		description_es:
			"Curso completo enfocado en la creación de aplicaciones web de alto rendimiento y enfocadas en contenido utilizando Astro. Cubre generación estática, renderizado del lado del servidor e híbrido, persistencia de estado, autenticación e integraciones con APIs. Incluye el uso de múltiples frameworks de UI (React, Vue, Solid), Astro DB y técnicas avanzadas de optimización para SEO y manejo de imágenes.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-05-11"),
		duration: "10 Hours",
		technologies: JSON.stringify([
			"OpenAI API",
			"NestJS",
			"React",
			"Vite",
			"TypeScript",
			"Assistant API",
			"Speech-to-Text",
			"Text-to-Speech",
			"Image Generation",
			"File Upload",
			"Custom AI Assistants"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/xddwahomij",
		title_en: "OpenAI: Practical Exercises and Assistants with React + NestJS",
		description_en:
			"Technical course focused on implementing OpenAI’s API with a full-stack TypeScript environment. Covers audio transcription and generation, image creation and editing through AI, and the use of the Assistant API for building custom intelligent agents. Includes backend integration with NestJS and frontend implementation using React + Vite.",
		title_es: "OpenAI: Ejercicios Prácticos y Asistentes con React + NestJS",
		description_es:
			"Curso técnico enfocado en la implementación de la API de OpenAI dentro de un entorno full-stack con TypeScript. Cubre generación y transcripción de audio, creación y edición de imágenes mediante inteligencia artificial, y uso de la Assistant API para construir asistentes personalizados. Incluye integración backend con NestJS e implementación frontend con React + Vite.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-05-11"),
		duration: "6 Hours",
		technologies: JSON.stringify([
			"Zustand",
			"React",
			"TypeScript",
			"Immer",
			"Axios",
			"Firebase",
			"LocalStorage",
			"SessionStorage",
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/hpqsp0cxal",
		title_en: "Mini-Course Zustand: State Management for React",
		description_en:
			"Focused course on modern state management with Zustand as a lightweight alternative to Redux, Redux Toolkit, or Context API. Covers middleware usage, persistence (local and remote), authentication flows, slices, and store subscriptions — all implemented with TypeScript and strict typing.",
		title_es: "Mini-Curso Zustand: Gestión de Estado para React",
		description_es:
			"Curso enfocado en la gestión moderna de estado con Zustand como alternativa ligera a Redux, Redux Toolkit o Context API. Cubre el uso de middlewares, persistencia local y remota, flujos de autenticación, slices y suscripciones de stores, todo implementado con TypeScript y tipado estricto.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-05-12"),
		duration: "16 Hours",
		technologies: JSON.stringify([
			"Socket.io",
			"React",
			"JWT",
			"MongoDB",
			"Mapbox",
			"RXJS",
			"Ant Design",
			"Bootstrap",
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/ercpez6xx8",
		title_en: "React: Real-Time Applications with Socket.io",
		description_en:
			"Comprehensive course on integrating websockets in React applications using Socket.io. Covers authentication with JWT, CRUD operations via sockets, event handling, and real-time features such as maps, queues, and chats. Includes reusable custom hooks and best practices for scalable real-time systems.",
		title_es: "React: Aplicaciones en Tiempo Real con Socket.io",
		description_es:
			"Curso completo sobre la integración de websockets en aplicaciones React utilizando Socket.io. Cubre autenticación con JWT, operaciones CRUD mediante sockets, manejo de eventos y funcionalidades en tiempo real como mapas, colas y chats. Incluye creación de hooks personalizados y buenas prácticas para sistemas escalables en tiempo real.",
	},
	{
		provider: "DevTalles",
		date: new Date("2025-10-19"),
		duration: "46 Hours",
		technologies: JSON.stringify([
			"React",
			"TypeScript",
			"Hooks",
			"Context API",
			"Redux Toolkit",
			"Zustand",
			"Vitest",
			"TailwindCSS",
			"ShadCN",
			"Node.js",
			"Express",
			"MongoDB",
			"JWT",
			"Testing Library",
			"React Compiler"
		]),
		certificateUrl: "https://cursos.devtalles.com/certificates/9mk7pwxp2t",
		title_en: "React: From Zero to Expert - 2025 Edition",
		description_en:
			"Comprehensive program covering modern React development from fundamentals to advanced practices. Focused on functional components, Hooks, and state management with Context API, Redux Toolkit, and Zustand. Includes TypeScript integration, unit and integration testing with Vitest, UI development with TailwindCSS and ShadCN, and backend connectivity using Node.js, Express, and MongoDB. Also explores authentication, performance optimization, and React Compiler for efficient rendering.",
		title_es: "React: de Cero a Experto - Edición 2025",
		description_es:
			"Programa integral que abarca el desarrollo moderno con React desde los fundamentos hasta prácticas avanzadas. Enfocado en componentes funcionales y Hooks, gestión de estado con Context API, Redux Toolkit y Zustand. Incluye integración con TypeScript, pruebas unitarias y de integración con Vitest, desarrollo de interfaces con TailwindCSS y ShadCN, y conexión con backend usando Node.js, Express y MongoDB. También aborda autenticación, optimización de rendimiento y uso de React Compiler para renderizado eficiente.",
	},

];