export const ProjectsSeed = [
    {
        title_en: "E-commerce Microservices Platform",
        title_es: "Plataforma de Microservicios para E-commerce",
        projectUrl: null,
        repositoryUrl: "https://github.com/orgs/Nest-Microservices-Course-AlanLB/repositories",
        mediaUrl: "/assets/projects/birds.jpg",
        mediaType: "image",
    },
    {
        title_en: "Clothing Store API",
        title_es: "API para Tienda de Ropa",
        projectUrl: null,
        repositoryUrl: "https://github.com/Alanlb195/NestJSTesloAPI",
        mediaUrl: "/assets/projects/measuring-cups.jpg",
        mediaType: "image",
    },
    {
        title_en: "Legacy Modernization with Docker",
        title_es: "Modernización de Aplicación Legacy con Docker",
        projectUrl: null,
        repositoryUrl: "https://github.com/Alanlb195/WebForms-Docker",
        mediaUrl: "/assets/projects/the-autumn.jpg",
        mediaType: "image",
    },
    {
        title_en: "E-commerce Microservices Platform",
        title_es: "Plataforma de Microservicios para E-commerce",
        projectUrl: null,
        repositoryUrl: "https://github.com/orgs/Nest-Microservices-Course-AlanLB/repositories",
        mediaUrl: "/assets/projects/walnuts.jpg",
        mediaType: "image",
    },
    {
        title_en: "Clothing Store API",
        title_es: "API para Tienda de Ropa",
        projectUrl: null,
        repositoryUrl: "https://github.com/Alanlb195/NestJSTesloAPI",
        mediaUrl: "/assets/projects/waterfall.jpg",
        mediaType: "image",
    },
    {
        title_en: "Legacy Modernization with Docker",
        title_es: "Modernización de Aplicación Legacy con Docker",
        projectUrl: null,
        repositoryUrl: "https://github.com/Alanlb195/WebForms-Docker",
        mediaUrl: "/assets/projects/calendar-app.png",
        mediaType: "image",
    },
];
